<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HP-chan" failures="6" tests="6" name="gr1.ar1.Test2" time="19.808" errors="0" timestamp="4 Nov 2021 18:53:08 GMT">
  <testcase classname="gr1.ar1.Test2" name="testEmail" time="3.989">
    <failure message="Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx" type="com.codoid.products.exception.FilloException">
      <![CDATA[com.codoid.products.exception.FilloException: Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx
	at com.codoid.products.fillo.InsertExcelUtil.saveWorkBook(InsertExcelUtil.java:134)
	at com.codoid.products.fillo.InsertExcelUtil.runInsertQuery(InsertExcelUtil.java:105)
	at com.codoid.products.fillo.Insert.executeInsert(Insert.java:48)
	at com.codoid.products.fillo.Connection.executeUpdate(Connection.java:97)
	at gr1.ar1.Test2Page.resultTest2Write(Test2Page.java:50)
	at gr1.ar1.Test2.testEmail(Test2.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testEmail -->
  <testcase classname="gr1.ar1.Test2" name="testLastName" time="3.330">
    <failure message="Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx" type="com.codoid.products.exception.FilloException">
      <![CDATA[com.codoid.products.exception.FilloException: Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx
	at com.codoid.products.fillo.InsertExcelUtil.saveWorkBook(InsertExcelUtil.java:134)
	at com.codoid.products.fillo.InsertExcelUtil.runInsertQuery(InsertExcelUtil.java:105)
	at com.codoid.products.fillo.Insert.executeInsert(Insert.java:48)
	at com.codoid.products.fillo.Connection.executeUpdate(Connection.java:97)
	at gr1.ar1.Test2Page.resultTest2Write(Test2Page.java:50)
	at gr1.ar1.Test2.testLastName(Test2.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testLastName -->
  <testcase classname="gr1.ar1.Test2" name="testNick" time="3.453">
    <failure message="Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx" type="com.codoid.products.exception.FilloException">
      <![CDATA[com.codoid.products.exception.FilloException: Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx
	at com.codoid.products.fillo.InsertExcelUtil.saveWorkBook(InsertExcelUtil.java:134)
	at com.codoid.products.fillo.InsertExcelUtil.runInsertQuery(InsertExcelUtil.java:105)
	at com.codoid.products.fillo.Insert.executeInsert(Insert.java:48)
	at com.codoid.products.fillo.Connection.executeUpdate(Connection.java:97)
	at gr1.ar1.Test2Page.resultTest2Write(Test2Page.java:50)
	at gr1.ar1.Test2.testNick(Test2.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testNick -->
  <testcase classname="gr1.ar1.Test2" name="testFirstName" time="3.305">
    <failure message="Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx" type="com.codoid.products.exception.FilloException">
      <![CDATA[com.codoid.products.exception.FilloException: Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx
	at com.codoid.products.fillo.InsertExcelUtil.saveWorkBook(InsertExcelUtil.java:134)
	at com.codoid.products.fillo.InsertExcelUtil.runInsertQuery(InsertExcelUtil.java:105)
	at com.codoid.products.fillo.Insert.executeInsert(Insert.java:48)
	at com.codoid.products.fillo.Connection.executeUpdate(Connection.java:97)
	at gr1.ar1.Test2Page.resultTest2Write(Test2Page.java:50)
	at gr1.ar1.Test2.testFirstName(Test2.java:74)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testFirstName -->
  <testcase classname="gr1.ar1.Test2" name="testLogin" time="2.741">
    <failure message="Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx" type="com.codoid.products.exception.FilloException">
      <![CDATA[com.codoid.products.exception.FilloException: Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx
	at com.codoid.products.fillo.InsertExcelUtil.saveWorkBook(InsertExcelUtil.java:134)
	at com.codoid.products.fillo.InsertExcelUtil.runInsertQuery(InsertExcelUtil.java:105)
	at com.codoid.products.fillo.Insert.executeInsert(Insert.java:48)
	at com.codoid.products.fillo.Connection.executeUpdate(Connection.java:97)
	at gr1.ar1.Test2Page.resultTest2Write(Test2Page.java:50)
	at gr1.ar1.Test2.testLogin(Test2.java:48)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="gr1.ar1.Test2" name="testPassword" time="2.990">
    <failure message="Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx" type="com.codoid.products.exception.FilloException">
      <![CDATA[com.codoid.products.exception.FilloException: Insert query cannot be proccesed, if File is already opened. File Path-..\ar1\src\login_data.xlsx
	at com.codoid.products.fillo.InsertExcelUtil.saveWorkBook(InsertExcelUtil.java:134)
	at com.codoid.products.fillo.InsertExcelUtil.runInsertQuery(InsertExcelUtil.java:105)
	at com.codoid.products.fillo.Insert.executeInsert(Insert.java:48)
	at com.codoid.products.fillo.Connection.executeUpdate(Connection.java:97)
	at gr1.ar1.Test2Page.resultTest2Write(Test2Page.java:50)
	at gr1.ar1.Test2.testPassword(Test2.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testPassword -->
</testsuite> <!-- gr1.ar1.Test2 -->
